FROM node:22.13.1-alpine AS build
 
 # Set the working directory
 WORKDIR /usr/src/app
 
 # Copy package.json and package-lock.json
 COPY package.json package-lock.json ./
 
 # Install dependencies
 RUN npm install
  ARG VITE_KEYCLOAK_SERVER_URL
  ARG VITE_KEYCLOAK_REALM
  ARG VITE_KEYCLOAK_CLIENT_ID
  ARG VITE_BASE_PATH
  ARG VITE_API_BASE_URL
  ARG VITE_WS_BASE_URL
  ARG VITE_API_BASE_PATH
  ARG VITE_MICROSTRATEGY_BASE_URL
  ARG VITE_MICROSTRATEGY_PROJECT_ID
  ARG VITE_MICROSTRATEGY_DASHBOARD_ID
  ARG VITE_POWERBI_CLIENT_ID
  ARG VITE_POWERBI_DEFAULT_WORKSPACE_ID
  ARG VITE_VITE_ALLOWED_HOSTS=$VITE_ALLOWED_HOSTS
  ARG VITE_MAX_FILE_SIZE
  ARG VITE_ALLOWED_FILE_TYPES
  ARG VITE_PYTHON_API_URL_PROD
  ARG VITE_PYTHON_API_URL_DEV
  ENV VITE_PYTHON_API_URL_DEV=$VITE_PYTHON_API_URL_DEV
  ENV VITE_PYTHON_API_URL_PROD=$VITE_PYTHON_API_URL_PROD
  ENV VITE_ALLOWED_FILE_TYPES=$VITE_ALLOWED_FILE_TYPES
  ENV VITE_MAX_FILE_SIZE=$VITE_MAX_FILE_SIZE
  ENV VITE_POWERBI_DEFAULT_WORKSPACE_ID=$VITE_POWERBI_DEFAULT_WORKSPACE_ID
  ENV VITE_POWERBI_CLIENT_ID=$VITE_POWERBI_CLIENT_ID
  ENV VITE_MICROSTRATEGY_DASHBOARD_ID=$VITE_MICROSTRATEGY_DASHBOARD_ID
  ENV VITE_MICROSTRATEGY_PROJECT_ID=$VITE_MICROSTRATEGY_PROJECT_ID
  ENV VITE_MICROSTRATEGY_BASE_URL=$VITE_MICROSTRATEGY_BASE_URL
  ENV VITE_API_BASE_PATH=$VITE_API_BASE_PATH
  ENV VITE_OKTA_ISSUER=$VITE_OKTA_ISSUER
  ENV VITE_OKTA_CLIENT_ID=$VITE_OKTA_CLIENT_ID
  ENV VITE_BASE_PATH=$VITE_BASE_PATH
  ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
  ENV VITE_ALLOWED_HOSTS=$VITE_ALLOWED_HOSTS
  ENV VITE_WS_BASE_URL=$VITE_WS_BASE_URL
 
 # Copy the rest of the application files
 COPY ./ ./
 # COPY .env .env
 
 # Build the application
 RUN npm run build
 
 # Use the official NGINX image for production
 FROM nginx:stable-alpine AS production
 
 # copy nginx configuration in side conf.d folder
 COPY --from=build /usr/src/app/nginx /etc/nginx/conf.d
 
 # Copy the build output from the dist folder into the Nginx html directory
 COPY --from=build /usr/src/app/dist /usr/share/nginx/html
 
 # Expose port 80 to allow access to the app

 EXPOSE 80
 
 # Run Nginx in the foreground
 ENTRYPOINT ["nginx", "-g", "daemon off;"]
